//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SimpleChat.proto
namespace SimpleChat
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgHello")]
  public partial class CMsgHello : global::ProtoBuf.IExtensible
  {
    public CMsgHello() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }

    private string _desc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMsgHello")]
  public partial class SMsgHello : global::ProtoBuf.IExtensible
  {
    public SMsgHello() {}
    
    private SimpleChat.SMsgHello.RET _returnValue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"returnValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public SimpleChat.SMsgHello.RET returnValue
    {
      get { return _returnValue; }
      set { _returnValue = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RET")]
    public enum RET
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=1)]
      OK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAILED", Value=2)]
      FAILED = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgChat")]
  public partial class CMsgChat : global::ProtoBuf.IExtensible
  {
    public CMsgChat() {}
    
    private string _chatMsg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chatMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string chatMsg
    {
      get { return _chatMsg; }
      set { _chatMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMsgChat")]
  public partial class SMsgChat : global::ProtoBuf.IExtensible
  {
    public SMsgChat() {}
    
    private string _sender;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sender
    {
      get { return _sender; }
      set { _sender = value; }
    }
    private string _chatMsg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"chatMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string chatMsg
    {
      get { return _chatMsg; }
      set { _chatMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMsgBye")]
  public partial class CMsgBye : global::ProtoBuf.IExtensible
  {
    public CMsgBye() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SMsgBye")]
  public partial class SMsgBye : global::ProtoBuf.IExtensible
  {
    public SMsgBye() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MESSAGE_ID")]
    public enum MESSAGE_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMSG_HELLO", Value=1)]
      CMSG_HELLO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMSG_HELLO", Value=2)]
      SMSG_HELLO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMSG_CHAT", Value=3)]
      CMSG_CHAT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMSG_CHAT", Value=4)]
      SMSG_CHAT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMSG_BYE", Value=5)]
      CMSG_BYE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SMSG_BYE", Value=6)]
      SMSG_BYE = 6
    }
  
}
